### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by nhaesler** [martinroob/ngx-i18nsupport#1]
Hi, great looking package!
But on installation, npm throws the following error for me:

`2023 error Linux 4.8.0-39-generic
2024 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "ngx-i18nsupport" "--save-dev"
2025 error node v7.2.1
2026 error npm  v3.10.10
2027 error path /home/nico/src/tradity-client/node_modules/ngx-i18nsupport/dist/xliffmerge/xliffmerge
2028 error code ENOENT
2029 error errno -2
2030 error syscall chmod
2031 error enoent ENOENT: no such file or directory, chmod '/home/nico/src/tradity-client/node_modules/ngx-i18nsupport/dist/xliffmerge/xliffmerge'
2032 error enoent ENOENT: no such file or directory, chmod '/home/nico/src/tradity-client/node_modules/ngx-i18nsupport/dist/xliffmerge/xliffmerge'
2032 error enoent This is most likely not a problem with npm itself
2032 error enoent and is related to npm not being able to find a file.
2033 verbose exit [ -2, true ]`

Seems to me like you didn't publish the dist file on npm?

**Comment by martinroob** [comment]
Hi,
Thousand thanks for that hint.
I never ever published an npm package before.
Here it was just a missing .npmignore file. The dist folder is included in my .gitignore, but of course it is needed in the npm.
I should think about some better installation testing after publishing.
