### ISSUE TITLE
Optionally do not merge source value into new translation unit value (leave blank)

### ISSUE THREAD

**Issue by akrueger** [martinroob/ngx-i18nsupport#103]
Hi, I'm really grateful to be using `xliffmerge` in my application. It's working as expected for new development and adding in newly added i18n tags and merging them with already translated tags. 

However, the one issue I'm running into is that other translation software interprets the source values going to the new translation as "translated". _TinyTranslator_ will consider matching source and target values as "untranslated" or "new", but the software we use ([POEditor](https://poeditor.com/)) just assumes this value has already been translated. The result is that after running xliffmerge, I always have 0 "untranslated" in POEditor. I imagine this may be a common approach by other language interchange software platforms as well.

Is there already an option to adjust this behavior? I can't seem to find it in the configuration--I have tried flipping the `useSourceAsTarget` flag, but that does not seem to change the behavior. Conceptually, I am trying to achieve the following behavior:

**Original**
Source (xmb)
`<msg id="1"><source>/location1</source>Hello</msg>`

EN (xtb)
`<translation id="1">Hello</translation>`

ES (xtb)
`<translation id="1">Hola</translation>`

**Source changed**: _new i18n tag added in Angular template_
Source (xmb)
```
`<msg id="1"><source>/location1</source>Hello</msg>`
`<msg id="2"><source>/location2</source>Goodbye</msg>`
```

EN (xtb)
```
<translation id="1">Hello</translation>
<translation id="2"></translation>
```

ES (xtb)
```
<translation id="1">Hola</translation>
<translation id="2"></translation>
```

I would be willing to attempt a PR if you could point me to relevant area of the xliffmerge lib file. I made a few attempts but wasn't able to find the right spot in the flow to change the behavior.

Thanks for your work!

**Comment by martinroob** [comment]
`useSourceAsTarget` is meant to do exactly what you want. 
But there seems to be a bug.
It does not work when using format xmb/xtb.
Will try to fix that soon.
