### ISSUE TITLE
Add option to json, to mark changed translations as "new"

### ISSUE THREAD

**Issue by lippoliv** [martinroob/ngx-i18nsupport#104]
Thank you for spending time on this nice extensions. Today I come up with an feature-request:

# Preperation

Lets assume the following Code:

```html
<h1 i18n="@@default.works.h1">
  Hier ist die Überschrift
</h1>
```

so we will have this element in our `messages.xlf`

```xml
<trans-unit id="default.works.h1" datatype="html">
  <source>
    Hier ist die Überschrift
  </source>
  <context-group purpose="location">
    <context context-type="sourcefile">app/default/default.component.html</context>
    <context context-type="linenumber">1</context>
  </context-group>
</trans-unit>
```

While using xliffmerge, we will have the following element in our `messages.en.xlf`

```xml
<trans-unit id="default.works.h1" datatype="html">
  <source>
    Hier ist die Überschrift
  </source>
  <target state="new"/>
  <context-group purpose="location">
    <context context-type="sourcefile">app/default/default.component.html</context>
    <context context-type="linenumber">1</context>
  </context-group>
</trans-unit>
```

So lets translate it:

```xml
<trans-unit id="default.works.h1" datatype="html">
  <source>
    Hier ist die Überschrift
  </source>
  <target state="final">
    Ths is the headline
  </target>
  <context-group purpose="location">
    <context context-type="sourcefile">app/default/default.component.html</context>
    <context context-type="linenumber">1</context>
  </context-group>
</trans-unit>
```

# Feature request

Well done for now. But as time goes on, there maybe will be an change on the original text

```html
<h1 i18n="@@default.works.h1">
  Hier war die Überschrift
</h1>
```

Now, while using xliffmerge, our `messages.en.xlf` will look like this:

```xml
<trans-unit id="default.works.h1" datatype="html">
  <source>
    Hier war die Überschrift
  </source>
  <target state="final">
    Ths is the headline
  </target>
  <context-group purpose="location">
    <context context-type="sourcefile">app/default/default.component.html</context>
    <context context-type="linenumber">1</context>
  </context-group>
</trans-unit>
```

As you can see, the "source" got updated, which is relly cool as my translator can update the Translation. BUT the state is still "final", so while having thousands of Translations, it is really hard to figure out which one has changed and to check if they Need an Translation-update.

So I would like to ask, if you can add an Option to `xliffmerge.json` to not just update `source` text, but also update the state of the `target` attribut to "new" (as it is).

That would help me, to make sure that changes in translations are updated across all languages. Combined with my [feature request on ng xi18n](https://github.com/angular/angular-cli/issues/12321) I can enforce this via CI Server.

**Comment by martinroob** [comment]
In this case state should not be "final", but "translated", see issue #101.
Will check, wether this works correct or not.

**Comment by lippoliv** [comment]
@martinroob OK I see. It works. Thanks for your fast Reply.

But I think here are two challenges, please read and think about:

# Code formatting
I do use IntelliJ. In IntelliJ I can enforce Code-Formatting before commiting. Using this, we can enforce an consistent code-Format across our Team. **BUT** translations get marked as "translated" through code-Generation:

**1. Code**

```xml
      <trans-unit id="default.works.h1" datatype="html">
        <source>
  Hier ist die Überschrift
</source>
        <target state="final">
          This is the headline
        </target>

        <context-group purpose="location">
          <context context-type="sourcefile">app/default/default.component.html</context>
          <context context-type="linenumber">1</context>
        </context-group>
      </trans-unit>
```

**2. Code (formatted)**
```xml
      <trans-unit id="default.works.h1" datatype="html">
        <source>
          Hier ist die Überschrift
        </source>
        <target state="final">
          This is the headline
        </target>

        <context-group purpose="location">
          <context context-type="sourcefile">app/default/default.component.html</context>
          <context context-type="linenumber">1</context>
        </context-group>
      </trans-unit>
```

**3. Code (just re-run xliffmerge)**
```xml
      <trans-unit id="default.works.h1" datatype="html">
        <source>
  Hier ist die Überschrift
</source>
        <target state="translated">
          This is the headline
        </target>

        <context-group purpose="location">
          <context context-type="sourcefile">app/default/default.component.html</context>
          <context context-type="linenumber">1</context>
        </context-group>
      </trans-unit>```

So here you see, we'll get a lot of "translated" states, for all of our translations. Can you ignore Whitespaces / TABs before and after the content to translate, while checking if the source translation has changed?

If you like, I can create a seperate issue here (doesn't really belong to this one)...

# Changed translations should be "new"

So for new translations we do run through the following life-cycle: `new`, `translated`, `final`.

**new** means, that the translation needs to be done.  
**translated** means, that the source was translated and needs to be checked (by Project Manager or Tester for example)
**final** means, that the translation was checked and found to be OK.

So when setting `translated` as a state for `final` targets, where the source has changed, I think this will hit the wrong person of the Team. `translated` will be checked by another guy (Project Manager / Tester) as `new` would be checked (Developer / Translator).

I think, changed translations should run through the same life-cycle as new one would do.

So to be dynamic, I think if you like my idea, you can by Default work like now, but adding the mentioned option so complex projects can choose what to do here.

**Comment by Seppo18** [comment]
Hi,

Thank you also from my behalf to spend time to do and maintain this extension. 

Could it be possible to do similar option also for new texts (ID is in master (messages.xlf) file but not in any language specific file) ?  In development phase text may contain errors and these errors aren't fixed into code.  Fixes are done only into generated (xliffmerge generates those files from master) xlf files.

Our project is still in early state and I'm not even sure do we use XLIFF v1.2 or 2.0 format. At least v2.0 state is simpler than v1.2. But this is totally different story....
[XLIFF v2.0 state](http://docs.oasis-open.org/xliff/xliff-core/v2.0/os/xliff-core-v2.0-os.html#state)
[XLIFF v1.2 state](http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#state)
