### ISSUE TITLE
Wrong line endings in bin

### ISSUE THREAD

**Issue by Sonaryr** [martinroob/ngx-i18nsupport#12]
Hi

it looks like you published your npm package from a windows machine, causing an issue on unix machines.
Can you fix this please, at the moment I did it by changing the file locally myself.
so you will need to convert `CRLF` to `LF` in `src/xliffmerge/xliffmerge`

**Comment by martinroob** [comment]
You are right, I'm using a Windows machine.
I will fix it soon.
Sorry for any inconvience.

**Comment by martinroob** [comment]
Second try in version 0.2.2.
Forgot to rebuild after the change.

**Comment by Sonaryr** [comment]
now https://github.com/martinroob/ngx-i18nsupport/blob/master/src/xliffmerge/xliffmerge#L2 breaks it

**Comment by martinroob** [comment]
*^!** it seems, that I'm unable to fix this bloody damned little file.
Sorry, give me another chance in the next hours...
