### ISSUE TITLE
Error on recompilation phase - False expression: Host should not return a redirect source file from `getSourceFile`

### ISSUE THREAD

**Issue by maku** [martinroob/ngx-i18nsupport#123]
I installed "ngx-i18nsupport" in an existing project to support i18n:

```
ng add @ngx-i18nsupport/tooling --i18nLocale=de --languages de,en
```

I marked a div with the i18n attribut, did the extraction phase (run extract-i18n) and the translation phase...

After that I started the project e.g. 
```
ng serve  --port 5600 --host 0.0.0.0 --proxy-config proxy.conf.json --configuration=en
```
Project compilation works fine and app works as expected (translated text was presented)
As soon as I change the source code and a project recompilation takes place I get the following error:

```
ERROR in Debug Failure. False expression: Host should not return a redirect source file from `getSourceFile`
i ｢wdm｣: Failed to compile.
```

Can anybody give me a hint what's the problem??

**Comment by martinroob** [comment]
Sorry, this has absolutely nothing to do with ngx-i18nsupport.
Please google your error message and you will find some hints.
