### ISSUE TITLE
WARNING: master says to have source-language="en", should be "en-gb"

### ISSUE THREAD

**Issue by Hainesy** [martinroob/ngx-i18nsupport#132]
I'm getting this warning on the command line for xliffmerge:

WARNING: master says to have source-language="en", should be "en-gb" (your defaultLanguage)
WARNING: changed master source-language="en" to "en-gb"

I can't find anywhere that specifies the source-language as "en" - wheres should this be set?

**Comment by Hainesy** [comment]
Then there's something wrong because we are setting this to en-gb

`ng xi18n web-app --i18n-format xlf --output-path i18n --i18n-locale en-gb`

**Comment by martinroob** [comment]
I tried it with angular 7.1.4 and could not reproduce the problem.
It writes `source-language="en-gb"` to messages.xlf as expected.

**Comment by Hainesy** [comment]
As I said, the source language is correct in messages.xlf, so I don't know why this warning is appearing at all. I can't find anywhere that specifies the source-language as "en".
