### ISSUE TITLE
Receive `Unexpected token }` while adding it with `ng add`

### ISSUE THREAD

**Issue by mfechner** [martinroob/ngx-i18nsupport#133]
I just wanted to test this very helpful project and followed the steps described here:
https://github.com/martinroob/ngx-i18nsupport/wiki/Tutorial-for-using-xliffmerge-with-angular-cli

I basically prepared my project by adding the required `i18n` directives to all required html tags.

I tried then to execute `ng add @ngx-i18nsupport/tooling`, but I get:
```
Skipping installation: Package already installed
? Which translation file format would you like to use? xlf
? Which default language do you use in your templates? en
? Which languages would you like to configure? (comma separated list like en,de,fr) en,de
    added script extract-i18n to //package.json
    added npm script to extract i18n message, run "npm run extract-i18n" for extraction
    added script start-de to //package.json
    added npm script to start app for language de, run "npm run start-de"
Unexpected token } in JSON at position 980
```

Has anyone an idea what the problem here could be?

**Comment by martinroob** [comment]
There are only 2 json-files involved, package.json and angular.json
Could you have a look at these 2 files too see what sort of syntax error happens?
I will try to reproduce it too.

**Comment by martinroob** [comment]
Tried to reproduce it.
Followed all the steps in the tutorial using latest version (ng 7.3.9,  @ngx-i18nsupport/tooling@1.1.3).
Could not reproduce the problem.
Maybe you can attach a copy of angular.json and package.json

**Comment by mfechner** [comment]
@martinroob sure, please find here the two files:
[angular.json.txt](https://github.com/martinroob/ngx-i18nsupport/files/3165289/angular.json.txt)
[package.json.txt](https://github.com/martinroob/ngx-i18nsupport/files/3165291/package.json.txt)

**Comment by martinroob** [comment]
There are a number of syntax errors in your angular.json (first is an extra comma at line 33).
So it is not parsable.
I guess you edited this file and made some mistakes here.

**Comment by mfechner** [comment]
@martinroob thanks a lot for your answer!
You are fully right, line 33 had a comma which should not be there.
This is clearly my mistake, sorry for this.

Now it is time to start playing with this very handy module, thanks a lot for your great work on it!

**Comment by mfechner** [comment]
As I just go over the diffs, maybe one improvement suggestion:
The outputPath definition currently is set to `"outputPath": "../dist/public",` if I execute the `ng add` command it adds a new configuration `"de": {`.

Would be nice if it could respect the previously existing `outputPath` definition and do not point to `dist/frontend-de` but `../dist/public/frontend-de`.

Not really important but would make it a little bit nicer.

Thanks again.

**Comment by villelahdenvuo** [comment]
@martinroob Actually the angular.json file supports comments, so you should use some JSON parser that supports them in the migration.
