### ISSUE TITLE
Suggestion: Initial State

### ISSUE THREAD

**Issue by ricardosaracino** [martinroob/ngx-i18nsupport#139]
not the end of the world but Podedit uses `<target state="needs-adaptation">` would be nice to be able to specify this on the command line ..

Thanks for the awesome tool

**Comment by lukengda** [comment]
xliffmerge uses the correct states specified within the xliff specs here: http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html. It might be poedit that is not respecting the correct states. Have you tried if poedit works better with xliff 2.0?

**Comment by ricardosaracino** [comment]
I havent... but this is a good suggestion. I guess the docs have been updated for version 8 and i had not refereed to them https://angular.io/guide/i18n#output-options

**Comment by martinroob** [comment]
The main problem with this spec is, that it is a little bit theoretical. How should a tool know wether a translation needs non textual information review an what does it mean?
And in xliff2 they totally changed the allowed states.
At the end the translator only needs to know wether he has to look at the translation or not.
So for xliffmerge I decided to only use the basic states to keep it simple.
