### ISSUE TITLE
xliffmerge - Modifying messages.*.xlf file of default language

### ISSUE THREAD

**Issue by tholok97** [martinroob/ngx-i18nsupport#145]
Hello, and **thank you** for this great tool. You saved us a lot of work these past few days.

Our default language is English. To speed up development we have been fixing typos and such by directly modifying the `messages.en.xlf` file. For example if the `<source>` text was "I liek Apples" we would change the `<target>` of that file to say "I like Apples". This works great for quick fixes, but now we want to run the tool again, and are having troubles.. The tool reverts all our changes for the default language, and forces the `<target>`s to match the `<source>`s.

**My question is**: is the expected behavoir of xliffmerge to forcefully update the `<target>`s in the `messages.en.xlf` file to match the `<source>` found in the `messages.xlf` file given that the default language is English?

**Comment by martinroob** [comment]
Thanks that you like xliffmerge.
The behaviour you describe in fact is the intended one.
The default language should be exactly what is given in the templates.

First of all every change of the source generates a new ID so that it will be a totally new unit. You can only avoid this by setting explicit IDs, which is very tedious and uncomfortable.

As a work around you could create a language like "en_corrected" to correct typos.

**Comment by tholok97** [comment]
Thank you for the rapid response. Alright, makes sense. Now we know the fault is on our side, and can act accordingly :+1:

I tried the workaround you suggest, but it is complaining that it is not a valid language code:
```
bash-4.4# ng add @ngx-i18nsupport/tooling --i18nLocale=en --languages en,fr,en_corrected
Skipping installation: Package already installed
? Which translation file format would you like to use? xlf
    "en_corrected" is not a valid language code.
"en_corrected" is not a valid language code.
```

My workaround for this is to give it some language we are not going to use, say `nor` for Norwegian, and then treat that as `en_corrected`.

Is it possible to have the tool allow us to input made-up language codes? Does the tool use the language code for anything other than distinguishing between the different `messages.*.xlf` files?

**Comment by martinroob** [comment]
Sorry, my fault. The _ is the problem. Must be "en-corrected"

**Comment by tholok97** [comment]
Ah! I see, thanks alot :+1: :+1: :+1:
