### ISSUE TITLE
Text of source language copied over to target language

### ISSUE THREAD

**Issue by MarcusRiemer** [martinroob/ngx-i18nsupport#149]
Currently whenever I add a new string to translate I have to hunt down the new string in the translated files because they are "pre-filled" with the text of the source language. This might be a shortcoming of the translation program I use (Poedit), but the behavior seems irritating to me nonetheless.

I am taking the following steps:

1) Add a text in my primarily german application:

```
<p i18n="@@extractTest">Dies ist ein deutscher Text</p>
```

2) I then run the following commands:

```
ng xi18n --i18n-locale de --output-path locale
ng run "blattwerkzeug-client:xliffmerge"
```

3) The updated `messages.en.xlf` now contains the following node:

```
<trans-unit id="extractTest" datatype="html">
   <source>Dies ist ein deutscher Text</source>
   <target state="new">Dies ist ein deutscher Text</target>
   <context-group purpose="location">
      <context context-type="sourcefile">app/front/templates/about.html</context>
      <context context-type="linenumber">20</context>
   </context-group>
</trans-unit>
```

As yoi can see the source text was copied over to the target. I do appreciate that the `state` is set to `new`, but it seems that at least Poedit simply ignores this. When I open the merged file I am greeted by the following sight:

![Result of xliffmerge in Poedit](https://i.imgur.com/PDdki6i.png)

Note that Poedit unhelpfully says "Translated: 95 of 95 (100%)" and that it is visually hard to find the string that requires attention. I will file a bugreport with Poedit as well, but would it be possibly to introduce a flag that disables this copying behaviour in the meantime? With Poedit this moves the untranslated unit to the top and also correctly updates the statusbar.

**Comment by vslavik** [comment]
FYI, Poedit 2.2.4 handles state="new" state correctly. I would argue that it is indeed not a great behavior to pre-fill the same string (which is never a correct translation), but as long as `state="new"` (or `state="initial"` in XLIFF 2) is used, it's a minor quibble.

**Comment by MarcusRiemer** [comment]
Oh, sorry for that. Seems that I have gotten too much in the habit of assuming that Arch Linux *always* ships the most recent version. At least in this case it doesn't.

Nevertheless I would still prefer to make the "copy" behaviour configurable. I guess it has been introduced to provide a fallback translation?

**Comment by martinroob** [comment]
There is the flag "`useSourceAsTarget`" that can be used to switch off this behaviour (by setting it to "false").
Originally the behaviour is there because Angular denied to aot compile an app if there were missing translations. And in this case it is better to have the original untranslated text to allow compilation.

**Comment by MarcusRiemer** [comment]
Wow, thanks to both of you for solving my problem. I have no idea how I didn't stumble over that aptly named flag ¯\_(ツ)_/¯
