### ISSUE TITLE
xliffmerge: use official Angular v9 i18n config

### ISSUE THREAD

**Issue by cyrilletuzi** [martinroob/ngx-i18nsupport#159]
First, thanks you for this amazing tool!

i18n is now much simpler in Angular 9, which introduces this config in `angular.json`:

```json
{
  "projects": {
    "helloworld": {
      "i18n": {
        "sourceLocale": "fr",
        "locales": {
          "en": "src/locale/messages.en.xlf"
} } } } }
```

So xliffmerge could get this config, if present, instead of its own custom config:
- `defaultLanguage` > from `sourceLocale`
- `languages` > from `locales` indexes
- `genDir` > from base path of one of `locales` values

It would simplify a lot, as most app would now just have to do `ng xi18n && xliffmerge` with no config at all.

**Comment by martinroob** [comment]
Thank you for your positive feedback.
This is definitively on my agenda for the next release.
I was a little bit short 8n time the last weeks.
But I plan to start with ng9 updates 7n the next few days.

**Comment by sandervanteinde** [comment]
@martinroob any updates on this?

**Comment by andrefilimono** [comment]
If nobody is working on this, I'd take a shot at it.

**Comment by julkue** [comment]
Since angular v11 is out now, it seems that it's finally incompatible.

```
An unhandled exception occurred: Cannot find module '@angular-devkit/architect'
```

**Comment by cyrilletuzi** [comment]
Closing this as it is untracked for some time now, and newer Angular versions, especially 11.1, may have new features that changes a lot of things.
