### ISSUE TITLE
Format xmb should create xtb files for translations

### ISSUE THREAD

**Issue by ocombe** [martinroob/ngx-i18nsupport#25]
Hello, when using this lib to handle the xmb format, it generates the correct source messages.xmb, but then for each locale to translate it will create a new translations file in xmb (ex: messages.xmb --> messages.fr.xmb).
The correct translation files for xmb are in the xtb format, and the syntax is different (`messagebundle` is now `translationbundle`, `msg` elements are now `translation` elements, ...).
This lib should create correct xtb files for the translations.

**Comment by martinroob** [comment]
Nice to know.
I never ever heard about xtb files before.
I will look for it and fix it soon.

**Comment by ocombe** [comment]
You can find an example of an xtb file here: https://github.com/angular/angular/blob/master/packages/compiler/test/i18n/serializers/xtb_spec.ts#L30-L42
