### ISSUE TITLE
String position(linenumber, sourcefile) only gets updated on new trans-units

### ISSUE THREAD

**Issue by rubyduby** [martinroob/ngx-i18nsupport#27]
Hi Martin,

i just found out, that the position of "older" trans-units only gets updated if there is a new trans-unit created by ng-xi18n first.

Maybe it would be possible to update while iterating over the nodes and comparing ids.

**Comment by martinroob** [comment]
Hi,
this should already be implemented in the newest version (0.6.0, 0.6.1).
Tell me if it is not working as expected with this version.
