### ISSUE TITLE
ERROR: language "en_US" is not valid

### ISSUE THREAD

**Issue by cburgmer** [martinroob/ngx-i18nsupport#33]
Our languages are country specific, so instead of `en` we have e.g. `en_US`. This does not seem to be supported right now, as with the following...

```
{
...
"languages": ["en_US"],
...
}
```

... I receive

```
$ node_modules/.bin/xliffmerge -p .xliffmerge
ERROR: language "en_US" is not valid
```

**Comment by martinroob** [comment]
Hello,
The correct code is "en-us".
The
Underscores are not allowed.
