### ISSUE TITLE
Invalid JSON for example config

### ISSUE THREAD

**Issue by cburgmer** [martinroob/ngx-i18nsupport#34]
Running the example config from the README, I receive the following output:

```
$ node_modules/.bin/xliffmerge -p .xliffmerge
ERROR: oops SyntaxError: Unexpected token } in JSON at position 349
~/my_project/node_modules/ngx-i18nsupport/dist/xliffmerge/xliff-merge.js:91
                throw err;
                ^

SyntaxError: Unexpected token } in JSON at position 349
    at JSON.parse (<anonymous>)
```

**Comment by martinroob** [comment]
Hmm,
For me the example configuration in the readme looks correct.
There are 2 opening and 2 closing braces.
Maybe you forgot to copy the first line?

**Comment by cburgmer** [comment]
I think the comma at the end of the line is wrong: `    "quiet": false,`

**Comment by martinroob** [comment]
You are right.
I corrected it.
Thanks
