### ISSUE TITLE
merging updated description and meaning

### ISSUE THREAD

**Issue by abierbaum** [martinroob/ngx-i18nsupport#44]
xmlifmerge is great, thank you so much for writing it.

One request I have is that when merging into existing language files, trans-units with the same id but with different description and meaning values could be updated with the new description and meaning.

I find that we do this once in a while where we get a question from a translator to clarify a given unit so we change the description text and want to get it into all the language files for all translators.

Is this something that could be supported?

**Comment by martinroob** [comment]
Hello
description and meaning are part of the id calculation of angular.
So changing them always changes the id and therefore there is no way to merge.

**Comment by abierbaum** [comment]
@martinroob True.  I was thinking of the case where the user specifies a custom ids.

So for example:

```
<h1 i18n="site header|An introduction header for this sample@@introductionHeader">Hello i18n!</h1>
```

If we generate the xliff files from this and have people translate, then later update the description and/or meaning it seems we could merge the changes in description and meaning into the existing files based upon the custom ids.

**Comment by martinroob** [comment]
I see what you mean.
Sounds reasonabless. 
I will fix it.
