### ISSUE TITLE
Absent Arabic automatic translation 

### ISSUE THREAD

**Issue by semla** [martinroob/ngx-i18nsupport#51]
Thank you for this tool. I tried automatic translation to German and it seems to work well. But when I tried Arabic 'ar' no translation was done, just the source copied.

**Comment by martinroob** [comment]
Hello,
Arabic is definitly on the list of supported languages:
Hello world!

مرحبا بالعالم!

Did you enable autotranslation in the config file?
You will also need an API key for Google Translate, e.g.
<pre>
"xliffmergeOptions": {
    ..,
   "languages": ["en", "ar"],
    "autotranslate": ["ar"],
    "apikey": "XYZ..your API Key",
</pre>
Then it should work.

**Comment by semla** [comment]
Sorry, my bad! I had forgotten to add "ar" to the autotranslate array
