### ISSUE TITLE
Auto Translation Bug

### ISSUE THREAD

**Issue by liuxinqiang** [martinroob/ngx-i18nsupport#52]
OS: Mac OS
Node: 8.4.0
Hi, This is my xliffmergeOptions, my default language is 'zh-CN', when I try to translate zh-CN to en with auto translation, I got the error message below:

`{
  "xliffmergeOptions": {
    "srcDir": "src/i18n",
    "genDir": "src/i18n",
    "i18nFile": "messages.xlf",
    "i18nFormat": "xlf",
    "encoding": "UTF-8",
    "defaultLanguage": "zh-CN",
    "languages": ["en", "ja"],
    "removeUnusedIds": true,
    "supportNgxTranslate": true,
    "useSourceAsTarget": false,
    "autotranslate": ["en"],
    "apikey": "***",
    "apikeyfile": "",
    "verbose": false,
    "quiet": false
  }
}`

`ERROR: autotranslate language "en" cannot be translated, because it is the source language
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! service-engine@0.0.0 translate:file: `ng xi18n --output-path src/i18n --locale zh-CN && xliffmerge --profile xliffmerge.json en ja`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the service-engine@0.0.0 translate:file script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liuxinqiang/.npm/_logs/2017-08-29T09_08_49_961Z-debug.log`

**Comment by martinroob** [comment]
You are right.
There is something wrong with the evaluation of language and default language.
It should work, if you do not set languages, when calling it, just use 

`.. && xliffmerge --profile xliffmerge.json`.

Or if you just add zh-CN as first language in profile and call.
Will fix it soon.
Sorry about that,

**Comment by martinroob** [comment]
Now I can reproduce it.
As a workaround you should try to run it with

`.. && xliffmerge --profile xliffmerge.json zh-CN en ja`

(just add zh-CN as first language).
autotranslate compares with the first given language instead of the default language.
As said, will fix it soon...

**Comment by martinroob** [comment]
It is fixed.
Please update to 0.8.5.
