### ISSUE TITLE
missing target tag

### ISSUE THREAD

**Issue by chaosmonster** [martinroob/ngx-i18nsupport#54]
since the master `messages.xlf` doesn't contain a `<target></target>` tag anymore the tag is also missing in the generated file. So either the tool should create a `<target state="new">Hello, world</target>` (prefered by me; maybe make it configurable) or change the readme.

Thanks for the tool :)

**Comment by martinroob** [comment]
You are right.
Currently it is based on the behaviour 6 months ago and they changed some things.

I will check and correct it.

**Comment by martinroob** [comment]
Just corrected the README and wiki page.
The creation of target can already be controlled using the option `useSourceAsTarget`.
So there is no need for a source change.
