### ISSUE TITLE
support for 'en_US' language format

### ISSUE THREAD

**Issue by kennanseno** [martinroob/ngx-i18nsupport#59]
Hi. it would be amazing if it supports 'en_US' language formats(not really sure what/if they have a name for that format). I can push a pr for this as it's just a small update.

**Comment by martinroob** [comment]
Hi,
actually it is implemented following RFC-3066, which says, there should be a hyphen in front of the region code.
So you can just use "en-US" which should work fine.
But I must confess that the underscore usage "en_US" is also very common, so you are right, it should bei supported.
I will fix it in the next version. 
A PR is always welcome, if you want to fix it by your own.

**Comment by kennanseno** [comment]
@martinroob #60

**Comment by martinroob** [comment]
fixed with version 0.9
