### ISSUE TITLE
Please only use my.app.key|ngx-translate and not @@my.app.key for ngx-translate entries

### ISSUE THREAD

**Issue by areijngoudt** [martinroob/ngx-i18nsupport#62]
For generating `.json files` for `ngx-translate`, `xliffmerge` now looks at both `i18n="my.app.key|ngx-translate"` and `i18n="@@my.app.key"` as markers which entries to include in the generated `.json files`. The latter (`i18n="@@my.app.key"`) is also used by the angular-cli extraction tool to use fixed ID's for the entries in the translation file. So these entries now also popup in the json files for ngx-translate where I don't need them. 

So please only use the first syntax (`i18n="my.app.key|ngx-translate"`) for selecting the entries for the ngx-translate json files.

**Comment by martinroob** [comment]
I see the problem.
To keep it compatible maybe there should be a configuration switch for controlling the behaviour.
Will habe a Lookup at it soon.

**Comment by martinroob** [comment]
@areijngoudt You can now achieve what you want by using version 0.10.0 and specifying `"ngxTranslateExtractionPattern": "ngx-translate"` in your profile. For description have a look at the wiki page.

**Comment by areijngoudt** [comment]
@martinroob - Works perfect. Thanks!
