### ISSUE TITLE
Could xlf output be better formatted

### ISSUE THREAD

**Issue by martinsik** [martinroob/ngx-i18nsupport#64]
I'm using `xliffmerge` right now and I was wondering if the output could be more human readable. For example now it generates output like this:

```
<target state="new">Name:</target></trans-unit><trans-unit id="380b43f6f630204545ad0e23c206e97c5c4bdecb" datatype="html">
  <source>Reward:</source>
        
<target state="new">Reward:</target><context-group purpose="location"><context context-type="sourcefile">example.component.ts</context><context context-type="linenumber">37</context></context-group></trans-unit><trans-unit id="ea71da1aed0ad121e79a8e73c0d66ec10c52e36d" datatype="html">  <source>Number of uses:</source>
        
<target state="new">Number of uses:</target><context-group purpose="location"><context context-type="sourcefile">example.component.ts</context><context context-type="linenumber">50</context></context-group></trans-unit><trans-unit id="3c02902d1e6bc749c646f88b6f7d3e019440df63" datatype="html">
```

While I would appreciate it to be more like this:

```
  <target state="new">Name:</target>
</trans-unit>

<trans-unit id="380b43f6f630204545ad0e23c206e97c5c4bdecb" datatype="html">
  <source>Reward:</source><target state="new">Reward:</target>
  <context-group purpose="location">
    <context context-type="sourcefile">example.component.ts</context>
    <context context-type="linenumber">37</context>
  </context-group>
</trans-unit>

<trans-unit id="ea71da1aed0ad121e79a8e73c0d66ec10c52e36d" datatype="html">  
  <source>Number of uses:</source><target state="new">Number of uses:</target>
  <context-group purpose="location">
    <context context-type="sourcefile">example.component.ts</context>
    <context context-type="linenumber">50</context>
  </context-group>
</trans-unit>

<trans-unit id="3c02902d1e6bc749c646f88b6f7d3e019440df63" datatype="html">
```

The output is correct of course but it's a little tedious to translate this right in the `xlf` file.

**Comment by martinroob** [comment]
Hi,
in principle you are absolutely right.
Unfortunately the output is just what the library I use for xml handling (xmldom) gives.
There is no good formatter available at the moment. At least I do not know one. 
So I am sorry that I cannot correct this. Maybe later.
Instead of translating manually by editing the ugly xml file you should think about using a translation tool (TinyTranslator is the one I suggest if course)

**Comment by evanliomain** [comment]
@martinsik I'm confronted to the same issue. I solve this by apply a little home made js script on the xlf files :

```javascript
const replace = require('replace-in-file');
const format = require('xmlfmt');
const fs = require('fs');
const xlfFilesPath = 'src/i18n/*.xlf';

// Remove leading and trailing whith space
const filesChanges1 = replace.sync({
  files: xlfFilesPath,
  from: [/^\s*/gm, /\s*$/gm],
  to: ''
});

// Remove \n to put all in 1 line
const filesChanges2 = replace.sync({
  files: xlfFilesPath,
  from: /\n/gm,
  to: ''
});

// Format xml files
[
  'src/i18n/messages.xlf',
  'src/i18n/messages.en.xlf',
  'src/i18n/messages.fr.xlf'
].forEach(file => {
  fs.writeFileSync(file, format(fs.readFileSync(file, 'utf8')));
});
```

It need `replace-in-file` and `xmlfmt` to work.

**Comment by martinsik** [comment]
@evanliomain I ended up using the following command to prettify the output:

```
npm i --save-dev pretty-xml
```

And then the following:

```
cat src/locale/messages.zh.xlf | node node_modules/.bin/pretty-xml > src/locale/messages.zh.xlf-new && rm src/locale/messages.zh.xlf && mv src/locale/messages.zh.xlf-new src/locale/messages.zh.xlf
```

**Comment by eweap** [comment]
@martinroob @martinsik Can't we add a `pretty-xml` call on the output before writing in the final xlf file ? (@martinroob thanks for your work btw !)

**Comment by martinroob** [comment]
This should be possible. I will have a look at it

**Comment by martinroob** [comment]
Starting with version 0.16.0 there is a new configuration parameter `beautifyOutput`. When it is set to `true` now `pretty-data` (the library beyond pretty-xml) will be used to format the output.

**Comment by eweap** [comment]
@martinroob Awesome ! Thanks a lot !

**Comment by kepner03** [comment]
Hi, if someone needs a better formatting and get the context-group removed. You can try my solution.
https://github.com/kepner03/angular-i18n-messagesXLF-cleaner 
Let me know if this can help you. :)

**Comment by TrueOleg** [comment]
> @martinsik I'm confronted to the same issue. I solve this by apply a little home made js script on the xlf files :
> 
> ```js
> const replace = require('replace-in-file');
> const format = require('xmlfmt');
> const fs = require('fs');
> const xlfFilesPath = 'src/i18n/*.xlf';
> 
> // Remove leading and trailing whith space
> const filesChanges1 = replace.sync({
>   files: xlfFilesPath,
>   from: [/^\s*/gm, /\s*$/gm],
>   to: ''
> });
> 
> // Remove \n to put all in 1 line
> const filesChanges2 = replace.sync({
>   files: xlfFilesPath,
>   from: /\n/gm,
>   to: ''
> });
> 
> // Format xml files
> [
>   'src/i18n/messages.xlf',
>   'src/i18n/messages.en.xlf',
>   'src/i18n/messages.fr.xlf'
> ].forEach(file => {
>   fs.writeFileSync(file, format(fs.readFileSync(file, 'utf8')));
> });
> ```
> 
> It need `replace-in-file` and `xmlfmt` to work.

Thanks

**Comment by JanneHarju** [comment]
Just here to say that I was totally missed this parameter. At least I found it now. This is gold. I was really frustrating with earlier dirty style how those files looks like. It was really hard to merge files and read them and edit them because there were several translations all in one line. Thank you for this feature.
