### ISSUE TITLE
xliffmerge removes trailing line break when there is an update

### ISSUE THREAD

**Issue by webmaster128** [martinroob/ngx-i18nsupport#66]
Hi and thanks for xliffmerge!

When xliffmerge changes a translation file, the trailing line break is removed. This is a bit annoying in the workflow because you need to revert the change manually.

![bildschirmfoto von 2018-02-01 13-27-59](https://user-images.githubusercontent.com/2603011/35678484-dfdb37d2-0753-11e8-8bba-2dae9b19547f.png)

The first diff is expected, the second is not.

The problem does not occur if there is no change in the translation.

**Comment by martinroob** [comment]
You are right. It is at least unexpected.
Will try to fix it soon.
