### ISSUE TITLE
Bug with "allowIdChange": true, it changes "new" to "translated"

### ISSUE THREAD

**Issue by xclayl** [martinroob/ngx-i18nsupport#68]
I have my messages.xlf files (with "new" targets).  I changed a i18n attribute from an explicit ID, i18n="@@myId", to autogenerated ID, and ran the tool.  The target in the DE file is now in the "translated" state.  It should remain "new".  In fact, it should ignore all existing "new" targets when re-ID'ing.

This tool is great BTW.  Love it.

**Comment by martinroob** [comment]
You are right, it is a bug.
Will fix it within the next days.
