### ISSUE TITLE
Add support to add a prefix to translated target languages

### ISSUE THREAD

**Issue by debslab** [martinroob/ngx-i18nsupport#70]
First, Thanks for the tool. One of my use for the tool is to verify that all displayed string in UI are part of i18n xliff. So I want in target language file, all the texts should have a prefix so that I will know that texts which miss translation. For example, in english, I have a string 'menu" in UI, then once I load a test language, I see that the caption is changed to '%%menu'. So can we have an option to add prefix in the target languages?

**Comment by martinroob** [comment]
Will add this as a new feature in the next days.

**Comment by martinroob** [comment]
There will be 2 new options `targetPraefix` and `targetSuffix` to set a praefix and a suffix.
Coming with 0.12

**Comment by debslab** [comment]
Thank you for quick fix. I am getting the result as intended.
