### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by mattrabe** [martinroob/ngx-i18nsupport#77]
I am using yarn, and was able to install the package using `yarn add ngx-i18nsupport`. However, subsequently running `xliffmerge` at the command line resulted in "Command not found." I tried closing my terminal and reopening in case the PATH needed to be updated, but it made no difference.

I'm not sure if this is related to installing via yarn instead of npm, something screwy in my path setup, or perhaps something else. For the time being, I have solved this by running with the relative path:`./node_modules/ngx-i18nsupport/dist/xliffmerge/xliffmerge`, which works but seems hackish.

If anyone has insight on why this might be happening I would be interested in hearing it.

By the way thank you for sharing the script @martinroob  - it works wonderfully and solves a critical problem.

**Comment by martinroob** [comment]
You can installl it with `yarn global add ngx-i18nsupport`, but maybe you still have to add it to your PATH. Just have a look at the yarn global documentation https://yarnpkg.com/lang/en/docs/cli/global/.
