### ISSUE TITLE
Placeholder index is invalid

### ISSUE THREAD

**Issue by krassx** [martinroob/ngx-i18nsupport#84]
Here is an <trans-unit> with two <bs-activity-stream-element> tag within its source and target.

```
<trans-unit id="8856d298b6fa89a339475c5d5cd20f2d2afcfbf7" datatype="html">
  <source>New <x id="START_TAG_BS-ACTIVITY-STREAM-ELEMENT" ctype="x-bs-activity-stream-element" equiv-text="&lt;bs-activity-stream-element>"/><x id="CLOSE_TAG_BS-ACTIVITY-STREAM-ELEMENT" ctype="x-bs-activity-stream-element" equiv-text="&lt;/bs-activity-stream-element>"/> was reported by <x id="START_TAG_BS-ACTIVITY-STREAM-ELEMENT_1" ctype="x-bs-activity-stream-element" equiv-text="&lt;bs-activity-stream-element>"/><x id="CLOSE_TAG_BS-ACTIVITY-STREAM-ELEMENT" ctype="x-bs-activity-stream-element" equiv-text="&lt;/bs-activity-stream-element>"/></source>
  <context-group purpose="location">
    <context context-type="sourcefile">app/elements/dashboard/activity-stream/elements-shared-activity-stream.component.ts</context>
    <context context-type="linenumber">127</context>
  </context-group>
  <target state="translated">新しい<x id="START_TAG_BS-ACTIVITY-STREAM-ELEMENT" ctype="x-bs-activity-stream-element"/><x id="CLOSE_TAG_BS-ACTIVITY-STREAM-ELEMENT" ctype="x-bs-activity-stream-element"/>によって報告された<x id="START_TAG_BS-ACTIVITY-STREAM-ELEMENT" ctype="x-bs-activity-stream-element"/><x id="CLOSE_TAG_BS-ACTIVITY-STREAM-ELEMENT" ctype="x-bs-activity-stream-element"/></target>
</trans-unit>
```
Look at `START_TAG_BS-ACTIVITY-STREAM-ELEMENT` in `source` and `target`. Former has correct `START_TAG_BS-ACTIVITY-STREAM-ELEMENT` and `START_TAG_BS-ACTIVITY-STREAM-ELEMENT_1`, whereas the latter has two `START_TAG_BS-ACTIVITY-STREAM-ELEMENT` (second one is missing "_1").

Here is the original line from the `messages.xlf` generated by `xi18n` tool

```
<source>New <x id="START_TAG_BS-ACTIVITY-STREAM-ELEMENT" ctype="x-bs-activity-stream-element" equiv-text="&lt;bs-activity-stream-element&gt;"/><x id="CLOSE_TAG_BS-ACTIVITY-STREAM-ELEMENT" ctype="x-bs-activity-stream-element" equiv-text="&lt;/bs-activity-stream-element&gt;"/> was reported by <x id="START_TAG_BS-ACTIVITY-STREAM-ELEMENT_1" ctype="x-bs-activity-stream-element" equiv-text="&lt;bs-activity-stream-element&gt;"/><x id="CLOSE_TAG_BS-ACTIVITY-STREAM-ELEMENT" ctype="x-bs-activity-stream-element" equiv-text="&lt;/bs-activity-stream-element&gt;"/></source>
```

And here is another problem - `xliffmerge` did not escape attribute value properly. Instead of
```
equiv-text="&lt;/bs-activity-stream-element&gt;"
```
it printed
```
equiv-text="&lt;/bs-activity-stream-element>"
```

**Comment by krassx** [comment]
Checked more cases and tt seems that index is lost when `autotranslate` is used.

**Comment by krassx** [comment]
Stepped through the code to find out the details of that misbehavior. It seems that method `createXmlRepresentationOfStartTagPart()` in `xliff-message-parser.ts` does not add indexes to the `id` attributes (`_1`, `_2`, etc).

**Comment by martinroob** [comment]
Yes, it is a bug. Will try to fix it soon. Thanks for your investigations.

**Comment by krassx** [comment]
Great! If you need any other info just let me know.

**Comment by martinroob** [comment]
I found out how to fix it.
But I cannot reproduce how you get the xlf containing the _1 id.
When I try to extract a text with 2 costum tags with same name, they both get ID "START_TAG_XY" with no _1 contained.
So what was your original template code that produced your xlf and what exact version of angular did you use?

**Comment by krassx** [comment]
Here is the actual line from the template

```
<ng-container i18n>New <bs-activity-stream-element [activity]="activity" [mode]="'issue-type'"></bs-activity-stream-element> was reported by <bs-activity-stream-element [activity]="activity" [mode]="'author'" (filter)="updateFilter($event)"></bs-activity-stream-element></ng-container>
```

Here is my env info

```
Angular CLI: 1.7.3
Node: 8.11.1
OS: darwin x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack-bundle-analyzer: 2.10.0
webpack: 3.11.0
```

And here is a gist with narrowed messages.xlf: https://gist.github.com/krassx/df7fc4cfd437796b5ff465bcebea983b (contains single trans-unit)

**Comment by martinroob** [comment]
Ahh! Now I got it.
The trick is, that there has to be an attribute that differs in the 2 tags.
So
`<p i18n>1: <app-comp></app-comp> 2: <app-comp></app-comp></p>`
will produce two time ID "START_TAG_APP-COMP".

But
`<p i18n>1: <app-comp x="1"></app-comp> 2: <app-comp x="2"></app-comp></p>`
will produce ID "START_TAG_APP-COMP" for first and "START_TAG_APP-COMP_1" for second.

**Comment by martinroob** [comment]
Concerning the other problem concerning `>` in `equiv-text="&lt;/bs-activity-stream-element>"`.
This in fact is not a bug.
The `>` is ok there, only the `<` has to be written as `&lt;`.
In fact the output is done by the serializer library I am using, so I cannot really change that without hacking/modifying this library (which I do not want to do).

Ok, it i a little bit confusing that xliffmerge changes `&gt;` to `>` but at should not disturb the following processes.

**Comment by krassx** [comment]
That special tags are used there intentionally to reduce the size of template. That `bs-activity-stream-element` accepts 9 types of activities and 5 modes which will bloat the template with at least 45 strings with lots of [$ngIf=""] or [*ngSwitch=""].

Anyway, thanks for the hint. I will review my templates once more and try to find another solution.
