### ISSUE TITLE
HTML entities

### ISSUE THREAD

**Issue by renatoferreirarenatoferreira** [martinroob/ngx-i18nsupport#86]
Hi,

I usually use HTML entities to add accents to my templates, but xliffmerge is always changing the character **&** to **&amp;amp;** while merging. These errors seem to be related:

```
[xmldom error]  entity not found:&atilde;
@#[line:18,col:140]
[xmldom error]  entity not found:&aacute;
@#[line:62,col:21]
[xmldom error]  entity not found:&aacute;
@#[line:90,col:114]
[xmldom error]  entity not found:&aacute;
@#[line:98,col:21]
[xmldom error]  entity not found:&ccedil;
@#[line:183,col:21]
[xmldom error]  entity not found:&atilde;
@#[line:183,col:21]
[xmldom error]  entity not found:&agrave;
@#[line:183,col:21]
[xmldom error]  entity not found:&ccedil;
@#[line:206,col:114]
[xmldom error]  entity not found:&atilde;
@#[line:206,col:114]
```

Am I doing something wrong?

Thanks!

Renato A. Ferreira

**Comment by martinroob** [comment]
This sounds like a bug. Will Check it soon.

**Comment by martinroob** [comment]
Sorry, I cannot reproduce it.
If I use e.g. <pre><p i18n>S&uuml;&szlig<p><pre> in a template, the ng x18n command already eliminates the HTML entities and in the xlf file I get something like <pre><source>Süß</source></pre>. Same with atilde, agrave, ....
What exactly do you use in your angular template?

**Comment by renatoferreirarenatoferreira** [comment]
Well... Let me show you how it is happening here.

Consider the following piece of xml data:

![image](https://user-images.githubusercontent.com/12613085/40116412-fb997df2-58e9-11e8-8fe1-bed1011eb62d.png)

Now I will add a random div tag in my code in order to force the xlf files to be updated (I am using angular xi18n). The command "ng xi18n" does not provide any relevant output.

Here goes the commando output. Observe specially the errors related to the line 55 that I am using in this example.

```
>xliffmerge -p xliffmerge.json
WARNING: merged 1 trans-units from master to "en"
WARNING: transferred 6 changed source content from master to "en"
[xmldom error]  entity not found:&atilde;
@#[line:18,col:140]
[xmldom error]  entity not found:&Ccedil;
@#[line:55,col:21]
[xmldom error]  entity not found:&Atilde;
@#[line:55,col:21]
[xmldom error]  entity not found:&aacute;
@#[line:62,col:21]
[xmldom error]  entity not found:&aacute;
@#[line:90,col:114]
[xmldom error]  entity not found:&aacute;
@#[line:98,col:21]
[xmldom error]  entity not found:&ccedil;
@#[line:180,col:21]
[xmldom error]  entity not found:&atilde;
@#[line:180,col:21]
[xmldom error]  entity not found:&agrave;
@#[line:180,col:21]
[xmldom error]  entity not found:&ccedil;
@#[line:203,col:114]
[xmldom error]  entity not found:&atilde;
@#[line:203,col:114]
[xmldom error]  entity not found:&ccedil;
@#[line:211,col:21]
[xmldom error]  entity not found:&atilde;
@#[line:211,col:21]
WARNING: merged 1 trans-units from master to "pt"
WARNING: transferred 6 changed source content from master to "pt"
WARNING: please translate file "src/locale/messages.pt.xlf" to target-language="pt"

>
```

That piece of data now looks like the following:

![image](https://user-images.githubusercontent.com/12613085/40116570-68feae6c-58ea-11e8-9a10-2f8aa7a89306.png)

In addition to that, my git diff also reports a lot of changes like this:
```
         </context-group>
-      <target state="final">Cria Novo Usu&aacute;rio</target></trans-unit>
+      <target state="final">Cria Novo Usu&amp;aacute;rio</target></trans-unit>
       <trans-unit id="cff1428d10d59d14e45edec3c735a27b5482db59" datatype="html">


         </context-group>
-      <target state="final">Usu&aacute;rios</target></trans-unit>
+      <target state="final">Usu&amp;aacute;rios</target></trans-unit>
       <trans-unit id="8011e20c5bbe51602d459a860fbf29b599b55edd" datatype="html">


-      <target state="final">
-        Confirmat&ccedil;&atilde;o precisa ser igual &agrave; senha.
+      <target state="translated">
+        Confirmat&amp;ccedil;&amp;atilde;o precisa ser igual &amp;agrave; senha.
       </target></trans-unit>
```

More information:
Angular 5.2.0 using the cli to generate the xlf files
Visual Studio Code 1.23
Windows 10

**Comment by martinroob** [comment]
Ah, now I understand the problem. You type these HTML entities directly into the xlf file.
This will not work (as you see). xlf is not an HTML dialect, so all these entities are not known.
(that is what the output "entity not found" says).

You can (and should)  just use the normal keyboard input of your portuguese keyboard, which should allow ypu to type ~A and so on.

In fact this is no specialty of ' xliffmerge`, but normal XML processing. The error is generated by the xmldom library when reading the xlf.

So I am sorry. Cannot fix this.
