### ISSUE TITLE
beautifyOutput option does not work

### ISSUE THREAD

**Issue by ngehlert** [martinroob/ngx-i18nsupport#88]
According to the documentation and the recent issue https://github.com/martinroob/ngx-i18nsupport/issues/64 (resulting in release 0.16) there is an option to beautify/pretty print the output.

However If I enable the option the output stays the same. I had a quick look over the merge request https://github.com/martinroob/ngx-i18nsupport/commit/2ee10a011e121edf844c7489038e6c980af979cb and to me it looks like just the option was implemented but not the logic afterwards to then use it. The option is passed into TranslationMessagesFileReader.save, however this method does not seem to use it at all.

Am I missing something? (Yes I checked that I have the latest version 0.16 installed ;) )

**Comment by martinroob** [comment]
Sorry for the late reply. Was in holiday vacation for a week.
Will check the issue as soon as possible.

**Comment by ngehlert** [comment]
let me know if you need help

**Comment by ngehlert** [comment]
that was quick. awesome :)
