### ISSUE TITLE
Could the beautifyOption leave translation text as is?

### ISSUE THREAD

**Issue by johannks** [martinroob/ngx-i18nsupport#92]
Hello Martin

Great job! Two minor questions:

1) Would it be possible to have the beautifier leave nodes which contain text alone? The beautification process currently adds whitespaces to the translation strings if they contain x-interpolations.

2) Would it also be possible to add sorting, preferably on the trans-unit's id? If the files are generated and translated iteratively during the development process, they all end up unsorted at the bottom which makes it difficult to get an overview.

Keep up the good work. It's really appreciated!

**Comment by martinroob** [comment]
Hello,
Short answer to question 1 is "no, it is not possible".
The beautifier behind (pretty-data) does not support it, so I had to find another lib or write my own.

To question no 2: Yes, it is possible to sort the entries. But in principle the generated files are not intended z
to direct editing. You should Uwe a translation tool that can sort the entries.

**Comment by johannks** [comment]
Hello Martin,

Fair enough. But why add a beautifier in the first place if the intent is not to allow direct editing?

On a similar note (without opening a new issue), is it possible to change the state in the target if the source string has changed? Right now, we manually change the state in all target files to state="review" (probably not xliff conform, but serves our purpose) when we update a source string in the code.
