### ISSUE TITLE
Suggested changes for documentation

### ISSUE THREAD

**Issue by marie-dk** [martinroob/ngx-i18nsupport#93]
Angular 6.0.5
ngx-translate/core@10.0.2
ngx-i18nsupport@0.16.2

The tutorial and documentation suggests `ng xi18n --output-path src/i18n`. But this will put messages.xlf in `src/src/i18n` instead of the expected `src/i18n`... and as a result xliffmerge fails.

So `ng xi18n` should just have `i18n` as the output-path and then `srcDir` and `genDir` for xliffmerge must be set to `src/i18n`... this should be noted as it can be a bit confusing for new users as my self :-)

Also, there is no `--locale` flag for `ng xi18n` . The correct name is `--i18n-locale`.

Thank you for providing this great tool.

**Comment by martinroob** [comment]
Thank you for your comment. Will correct it soon.

**Comment by martinroob** [comment]
It is now Integrated in the tutorial
