### ISSUE TITLE
Enhancement: Multiple source files

### ISSUE THREAD

**Issue by Darkein** [martinroob/ngx-i18nsupport#98]
Hello,

I have an application with 2 source files, one generated from my web app, and the other for some translations loaded from an API.
Because my angular app is waiting for only one translation file, do you think it could be possible to use 2 source files to generate the target files?

Thanks!

Pierre

**Comment by martinroob** [comment]
In principle this is of course possible.
But angular would not use the IDs from your API generated parts, because it does not know there IDs. 

Maybe you can explain a little bit more what you want to achieve.

**Comment by Darkein** [comment]
That's right, It will only work with manual ids and [i18n-polyfill](https://github.com/ngx-translate/i18n-polyfill)

I need another translation file because i get some untranslated items (but with a translation key) from an api. Because i can't load a translation file dynamically, i must get and merge it with the existing translation file before loading the website

**Comment by Darkein** [comment]
love these ideas :)

**Comment by Darkein** [comment]
Hello,
I've found a node utility whose working like your xliffjoin solution, [xlf-merge](https://github.com/jaroslavsvak/xlf-merge). The author just done a little modification to works with source files (thanks!).
So it's up to you if you want to update xliffmerge, but thanks for your proposals :)

**Comment by martinroob** [comment]
Thanks for the link. Yes, that is exactly what I had in mind with "xliffjoin", except that it only supports xlf1.2, but that should not be a big issue.
So I will not work on somethink like this in the moment.
